#!/bin/bash
SHELL=/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/root/.local/bin

# MySQL database credentials
DB_USER='root'
DB_PASS='y3st45@#$'

# Create a directory with the current date for SQL backups
mkdir -p /var/www/Backups/DB/$(date +%F)
#mkdir -p "/var/www/Backups/DB/$(date +%F)"

# Get the list of DBs in the MySQL server
mysql -u"$DB_USER" -p"$DB_PASS" -e "show databases" | grep -v -E "^Database|information_schema|performance_schema|phpmyadmin" > "/var/www/Backups/DB/$(date +%F)/dblist.txt"

# Dump each database and save it in the backup directory
cat "/var/www/Backups/DB/$(date +%F)/dblist.txt" | while read i; do
    mysqldump -u"$DB_USER" -p"$DB_PASS" "$i" > "/var/www/Backups/DB/$(date +%F)/$i-db-bak-$(date +%F).sql"
done
cd /var/www/Backups/DB/$(date +%F)

#sending files to the backup server
curdate=`date +%Y-%m-%-d`
HOST='u229864.your-storagebox.de'
USER='u229864'
PASSWD='jLWP6xnL78HxiPTG'

ftp -pnv $HOST <<EOF
user $USER $PASSWD
prompt
mkdir /Staging-server-135/DB/$curdate
cd /Staging-server-135/DB/$curdate
mput *.sql
ls -la
bye
EOF

#removing the files from local
rm -rf /var/www/Backups/DB/$(date --iso)
