#!/bin/bash
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


############################### Backing up Plesk server Domain Files ###############################
echo -e "\n`date` - Backing up staging server Files..." >> $BACKUPLOG
mkdir -p /var/www/Backups/FILES/$(date --iso)
cd /var/www/Backups/FILES/$(date --iso)/

tar zcvf 2topadmindev.clienturls.com-$(date +%F).tar.gz /var/www/2topadmindev.clienturls.com
tar zcvf insulationsnakes.essentialdemo.com-$(date +%F).tar.gz /var/www/insulationsnakes.essentialdemo.com
tar zcvf marbleapi-stage.essentialdemo.com-$(date +%F).tar.gz /var/www/marbleapi-stage.essentialdemo.com
tar zcvf mobile-shop.clienturls.com-$(date +%F).tar.gz /var/www/mobile-shop.clienturls.com
tar zcvf onelinkstageapi.customerdemourl.com-$(date +%F).tar.gz /var/www/onelinkstageapi.customerdemourl.com
tar zcvf paterson-wp.essentialdemo.com-$(date +%F).tar.gz /var/www/paterson-wp.essentialdemo.com
tar zcvf po-ack-api.customerdemourl.com-$(date +%F).tar.gz /var/www/po-ack-api.customerdemourl.com
tar zcvf transportlogistics.essentialdemo.com-$(date +%F).tar.gz /var/www/transportlogistics.essentialdemo.com



############## Copying Backup to FTP Server #################

curdate=`date +%Y-%m-%-d`
HOST='u229864.your-storagebox.de'
USER='u229864'
PASSWD='jLWP6xnL78HxiPTG'

ftp -pnv $HOST <<EOF
user $USER $PASSWD
prompt 
mkdir /Staging-server-135/FILES/$curdate
cd /Staging-server-135/FILES/$curdate
mput *.tar.gz
ls -la
bye
EOF


rm -rf /var/www/Backups/FILES/$(date --iso)